version: '2'
services:
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
  benchmark:
    container_name: benchmark
    image: benchmark
    volumes:
      - ./sharedData:/sharedData
      - ./results:/results
    depends_on:
      - couchdb
    links:
      - couchdb
