apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc4
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-node4
  template:
    metadata:
      labels:
        name: mongo-node4
        instance: pepe
    spec:
      containers:
      - name: mongo-node4
        image: mongo
        command:
         - mongod
         - "--replSet"
         - my_replica_set
        ports:
        - containerPort: 27017
