---
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    name: mongo-rc
  name: mongo-rc1
spec: 
  replicas: 1
  selector: 
    name: mongo-node1
  template: 
    metadata: 
      labels: 
        instance: rod
        name: mongo-node1
    spec: 
      containers: 
        - 
          command: 
            - mongod
            - "--replSet"
            - my_replica_set
          image: mongo
          name: mongo-node1
          ports: 
            - 
              containerPort: 27017
