apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc2
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector: 
    name: mongo-node2
  template:
    metadata:
      labels:
        name: mongo-node2
        instance: jane
    spec:
      containers:
      - name: mongo-node2
        image: mongo
        command:
         - mongod
         - "--replSet"
         - my_replica_set 
        ports: 
        - containerPort: 27017
